<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Fleetify.Core\Fleetify.Core.csproj" />
    <ProjectReference Include="..\Fleetify.Protocol\Fleetify.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="BouncyCastle.Cryptography" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Fleetify.Infrastructure.Tests" />
  </ItemGroup>
</Project>
