<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Fleeto.Core\Fleeto.Core.csproj" />
    <ProjectReference Include="..\Fleeto.Protocol\Fleeto.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="BouncyCastle.Cryptography" />
    <PackageReference Include="Konscious.Security.Cryptography.Argon2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Fleeto.Infrastructure.Tests" />
  </ItemGroup>
</Project>
