// Agent protocol v1 between the Fleeto agent and fleetify-gateway.
//
// Transport:
//   CA:         HTTPS GET https://<agent host>/v1/ca returns the instance CA certificates as a PEM bundle. The agent
//               fetches it without sending anything secret, picks the CA whose SHA-256 (of the DER) equals the
//               fingerprint from the install command, and refuses to continue if none matches. (TLS stacks do not send
//               a self-signed root in the handshake, so the CA cannot be taken from the chain.)
//   Enrollment: HTTPS POST https://<agent host>/v1/enroll, body EnrollRequest, Content-Type application/x-protobuf,
//               over a connection verified normally against that CA as the only root, for the agent host name.
//               200 with EnrollResponse, or a problem+json error (400 invalid, 401 token refused, 429, 503 retry).
//   Session:    WebSocket wss://<agent host>/v1/connect with the agent client certificate (mTLS).
//               Every binary WebSocket message is exactly one AgentMessage (agent to server) or ServerMessage
//               (server to agent). The WebSocket frame is the length prefix. Maximum message size 4 MiB.
//
// Signatures (ed25519, instance signing key) cover "fleetify-agent-config-v1" || 0x00 || payload, where payload
// is the exact serialized bytes carried in SignedConfig.payload. The agent never re-serializes before verifying.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tier int32

const (
	Tier_TIER_UNSPECIFIED Tier = 0
	Tier_TIER_AGENT_ONLY  Tier = 1
	Tier_TIER_MANAGED     Tier = 2
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "TIER_AGENT_ONLY",
		2: "TIER_MANAGED",
	}
	Tier_value = map[string]int32{
		"TIER_UNSPECIFIED": 0,
		"TIER_AGENT_ONLY":  1,
		"TIER_MANAGED":     2,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type CheckType int32

const (
	CheckType_CHECK_TYPE_UNSPECIFIED CheckType = 0
	// value: average CPU usage in percent over the sample window.
	CheckType_CHECK_TYPE_CPU_USAGE CheckType = 1
	// value: physical memory in use, in percent.
	CheckType_CHECK_TYPE_MEMORY_USAGE CheckType = 2
	// value: free space in percent. One result per drive, target = drive.
	CheckType_CHECK_TYPE_DISK_FREE CheckType = 3
	// value: 1 running, 0 not running. target = service name. error when the service does not exist.
	CheckType_CHECK_TYPE_SERVICE_RUNNING CheckType = 4
	// value: days since boot, with decimals.
	CheckType_CHECK_TYPE_UPTIME CheckType = 5
)

// Enum value maps for CheckType.
var (
	CheckType_name = map[int32]string{
		0: "CHECK_TYPE_UNSPECIFIED",
		1: "CHECK_TYPE_CPU_USAGE",
		2: "CHECK_TYPE_MEMORY_USAGE",
		3: "CHECK_TYPE_DISK_FREE",
		4: "CHECK_TYPE_SERVICE_RUNNING",
		5: "CHECK_TYPE_UPTIME",
	}
	CheckType_value = map[string]int32{
		"CHECK_TYPE_UNSPECIFIED":     0,
		"CHECK_TYPE_CPU_USAGE":       1,
		"CHECK_TYPE_MEMORY_USAGE":    2,
		"CHECK_TYPE_DISK_FREE":       3,
		"CHECK_TYPE_SERVICE_RUNNING": 4,
		"CHECK_TYPE_UPTIME":          5,
	}
)

func (x CheckType) Enum() *CheckType {
	p := new(CheckType)
	*p = x
	return p
}

func (x CheckType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (CheckType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x CheckType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckType.Descriptor instead.
func (CheckType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

type DisconnectCode int32

const (
	DisconnectCode_DISCONNECT_CODE_UNSPECIFIED DisconnectCode = 0
	// Certificate revoked or endpoint deleted. The agent stops reconnecting and reports that it needs enrollment.
	DisconnectCode_DISCONNECT_CODE_REVOKED DisconnectCode = 1
	// Another live connection uses the same certificate.
	DisconnectCode_DISCONNECT_CODE_DUPLICATE_IDENTITY DisconnectCode = 2
	// Gateway shutting down; reconnect with backoff.
	DisconnectCode_DISCONNECT_CODE_SERVER_SHUTDOWN DisconnectCode = 3
	DisconnectCode_DISCONNECT_CODE_PROTOCOL_ERROR  DisconnectCode = 4
)

// Enum value maps for DisconnectCode.
var (
	DisconnectCode_name = map[int32]string{
		0: "DISCONNECT_CODE_UNSPECIFIED",
		1: "DISCONNECT_CODE_REVOKED",
		2: "DISCONNECT_CODE_DUPLICATE_IDENTITY",
		3: "DISCONNECT_CODE_SERVER_SHUTDOWN",
		4: "DISCONNECT_CODE_PROTOCOL_ERROR",
	}
	DisconnectCode_value = map[string]int32{
		"DISCONNECT_CODE_UNSPECIFIED":        0,
		"DISCONNECT_CODE_REVOKED":            1,
		"DISCONNECT_CODE_DUPLICATE_IDENTITY": 2,
		"DISCONNECT_CODE_SERVER_SHUTDOWN":    3,
		"DISCONNECT_CODE_PROTOCOL_ERROR":     4,
	}
)

func (x DisconnectCode) Enum() *DisconnectCode {
	p := new(DisconnectCode)
	*p = x
	return p
}

func (x DisconnectCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisconnectCode) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[2].Descriptor()
}

func (DisconnectCode) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[2]
}

func (x DisconnectCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisconnectCode.Descriptor instead.
func (DisconnectCode) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The enrollment token from the install command: fet_<id>_<secret>.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// PKCS#10 certificate signing request, ECDSA P-256, DER.
	CsrDer        []byte  `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	Hostname      string  `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            *OsInfo `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	AgentVersion  string  `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetOs() *OsInfo {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type EnrollResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EndpointId string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	InstanceId string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Agent certificate, DER. Valid 90 days.
	CertificateDer []byte `protobuf:"bytes,3,opt,name=certificate_der,json=certificateDer,proto3" json:"certificate_der,omitempty"`
	// Instance CA certificate, DER. The agent pins it.
	CaCertificateDer []byte `protobuf:"bytes,4,opt,name=ca_certificate_der,json=caCertificateDer,proto3" json:"ca_certificate_der,omitempty"`
	// Raw 32-byte ed25519 public key of the instance signing key. The agent pins it.
	InstanceSigningPublicKey []byte `protobuf:"bytes,5,opt,name=instance_signing_public_key,json=instanceSigningPublicKey,proto3" json:"instance_signing_public_key,omitempty"`
	InstanceSigningKeyId     string `protobuf:"bytes,6,opt,name=instance_signing_key_id,json=instanceSigningKeyId,proto3" json:"instance_signing_key_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *EnrollResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *EnrollResponse) GetCertificateDer() []byte {
	if x != nil {
		return x.CertificateDer
	}
	return nil
}

func (x *EnrollResponse) GetCaCertificateDer() []byte {
	if x != nil {
		return x.CaCertificateDer
	}
	return nil
}

func (x *EnrollResponse) GetInstanceSigningPublicKey() []byte {
	if x != nil {
		return x.InstanceSigningPublicKey
	}
	return nil
}

func (x *EnrollResponse) GetInstanceSigningKeyId() string {
	if x != nil {
		return x.InstanceSigningKeyId
	}
	return ""
}

type OsInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// windows, linux or darwin.
	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	// Product name, e.g. "Windows 11 Pro" or "Windows Server 2022 Standard".
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Version and build, e.g. "10.0.26200".
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// True for server editions.
	IsServer bool `protobuf:"varint,4,opt,name=is_server,json=isServer,proto3" json:"is_server,omitempty"`
	// amd64 or arm64.
	Architecture  string `protobuf:"bytes,5,opt,name=architecture,proto3" json:"architecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OsInfo) Reset() {
	*x = OsInfo{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OsInfo) ProtoMessage() {}

func (x *OsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OsInfo.ProtoReflect.Descriptor instead.
func (*OsInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *OsInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *OsInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OsInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OsInfo) GetIsServer() bool {
	if x != nil {
		return x.IsServer
	}
	return false
}

func (x *OsInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Inventory
	//	*AgentMessage_CheckResults
	//	*AgentMessage_RenewCertificate
	//	*AgentMessage_ConfigApplied
	//	*AgentMessage_Pong
	Body          isAgentMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentMessage) GetBody() isAgentMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetInventory() *InventoryReport {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Inventory); ok {
			return x.Inventory
		}
	}
	return nil
}

func (x *AgentMessage) GetCheckResults() *CheckResultBatch {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_CheckResults); ok {
			return x.CheckResults
		}
	}
	return nil
}

func (x *AgentMessage) GetRenewCertificate() *RenewCertificateRequest {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_RenewCertificate); ok {
			return x.RenewCertificate
		}
	}
	return nil
}

func (x *AgentMessage) GetConfigApplied() *ConfigApplied {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_ConfigApplied); ok {
			return x.ConfigApplied
		}
	}
	return nil
}

func (x *AgentMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isAgentMessage_Body interface {
	isAgentMessage_Body()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Inventory struct {
	Inventory *InventoryReport `protobuf:"bytes,3,opt,name=inventory,proto3,oneof"`
}

type AgentMessage_CheckResults struct {
	CheckResults *CheckResultBatch `protobuf:"bytes,4,opt,name=check_results,json=checkResults,proto3,oneof"`
}

type AgentMessage_RenewCertificate struct {
	RenewCertificate *RenewCertificateRequest `protobuf:"bytes,5,opt,name=renew_certificate,json=renewCertificate,proto3,oneof"`
}

type AgentMessage_ConfigApplied struct {
	ConfigApplied *ConfigApplied `protobuf:"bytes,6,opt,name=config_applied,json=configApplied,proto3,oneof"`
}

type AgentMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,7,opt,name=pong,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Body() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Body() {}

func (*AgentMessage_Inventory) isAgentMessage_Body() {}

func (*AgentMessage_CheckResults) isAgentMessage_Body() {}

func (*AgentMessage_RenewCertificate) isAgentMessage_Body() {}

func (*AgentMessage_ConfigApplied) isAgentMessage_Body() {}

func (*AgentMessage_Pong) isAgentMessage_Body() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerMessage_HelloAck
	//	*ServerMessage_BatchAck
	//	*ServerMessage_Config
	//	*ServerMessage_RenewCertificate
	//	*ServerMessage_Ping
	//	*ServerMessage_Disconnect
	//	*ServerMessage_InventoryRequest
	Body          isServerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMessage) GetBody() isServerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ServerMessage) GetBatchAck() *BatchAck {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_BatchAck); ok {
			return x.BatchAck
		}
	}
	return nil
}

func (x *ServerMessage) GetConfig() *SignedConfig {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ServerMessage) GetRenewCertificate() *RenewCertificateResponse {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_RenewCertificate); ok {
			return x.RenewCertificate
		}
	}
	return nil
}

func (x *ServerMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ServerMessage) GetDisconnect() *Disconnect {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

func (x *ServerMessage) GetInventoryRequest() *InventoryRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_InventoryRequest); ok {
			return x.InventoryRequest
		}
	}
	return nil
}

type isServerMessage_Body interface {
	isServerMessage_Body()
}

type ServerMessage_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ServerMessage_BatchAck struct {
	BatchAck *BatchAck `protobuf:"bytes,2,opt,name=batch_ack,json=batchAck,proto3,oneof"`
}

type ServerMessage_Config struct {
	Config *SignedConfig `protobuf:"bytes,3,opt,name=config,proto3,oneof"`
}

type ServerMessage_RenewCertificate struct {
	RenewCertificate *RenewCertificateResponse `protobuf:"bytes,4,opt,name=renew_certificate,json=renewCertificate,proto3,oneof"`
}

type ServerMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

type ServerMessage_Disconnect struct {
	Disconnect *Disconnect `protobuf:"bytes,6,opt,name=disconnect,proto3,oneof"`
}

type ServerMessage_InventoryRequest struct {
	InventoryRequest *InventoryRequest `protobuf:"bytes,7,opt,name=inventory_request,json=inventoryRequest,proto3,oneof"`
}

func (*ServerMessage_HelloAck) isServerMessage_Body() {}

func (*ServerMessage_BatchAck) isServerMessage_Body() {}

func (*ServerMessage_Config) isServerMessage_Body() {}

func (*ServerMessage_RenewCertificate) isServerMessage_Body() {}

func (*ServerMessage_Ping) isServerMessage_Body() {}

func (*ServerMessage_Disconnect) isServerMessage_Body() {}

func (*ServerMessage_InventoryRequest) isServerMessage_Body() {}

// First message after the WebSocket opens. The server closes the connection if anything else comes first.
type Hello struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Hostname     string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os           *OsInfo                `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	// Version of the signed configuration currently applied, 0 when none.
	ConfigVersion uint64 `protobuf:"varint,4,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// Hash of the last inventory the agent sent; the server requests a new report when it differs from its copy.
	InventoryHash string `protobuf:"bytes,5,opt,name=inventory_hash,json=inventoryHash,proto3" json:"inventory_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetOs() *OsInfo {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *Hello) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *Hello) GetInventoryHash() string {
	if x != nil {
		return x.InventoryHash
	}
	return ""
}

type HelloAck struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EndpointId string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	ServerTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// Interval for Heartbeat messages until a signed configuration says otherwise.
	HeartbeatIntervalSeconds uint32 `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HelloAck) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *HelloAck) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *HelloAck) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentTime     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=agent_time,json=agentTime,proto3" json:"agent_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetAgentTime() *timestamppb.Timestamp {
	if x != nil {
		return x.AgentTime
	}
	return nil
}

// Liveness probe, e.g. when a second connection with the same certificate arrives.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Ping) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Pong) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type InventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryRequest) Reset() {
	*x = InventoryRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryRequest) ProtoMessage() {}

func (x *InventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryRequest.ProtoReflect.Descriptor instead.
func (*InventoryRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

type InventoryReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hex SHA-256 over the deterministic serialization of inventory, computed by the agent.
	Hash          string     `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Inventory     *Inventory `protobuf:"bytes,2,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReport) Reset() {
	*x = InventoryReport{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReport) ProtoMessage() {}

func (x *InventoryReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReport.ProtoReflect.Descriptor instead.
func (*InventoryReport) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *InventoryReport) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *InventoryReport) GetInventory() *Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type Inventory struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Hostname             string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os                   *OsInfo                `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Manufacturer         string                 `protobuf:"bytes,3,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model                string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SerialNumber         string                 `protobuf:"bytes,5,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	CpuModel             string                 `protobuf:"bytes,6,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	CpuCores             uint32                 `protobuf:"varint,7,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuLogicalProcessors uint32                 `protobuf:"varint,8,opt,name=cpu_logical_processors,json=cpuLogicalProcessors,proto3" json:"cpu_logical_processors,omitempty"`
	MemoryTotalBytes     uint64                 `protobuf:"varint,9,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	Disks                []*Disk                `protobuf:"bytes,10,rep,name=disks,proto3" json:"disks,omitempty"`
	NetworkInterfaces    []*NetworkInterface    `protobuf:"bytes,11,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	Software             []*SoftwareItem        `protobuf:"bytes,12,rep,name=software,proto3" json:"software,omitempty"`
	BootTime             *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`
	Domain               string                 `protobuf:"bytes,14,opt,name=domain,proto3" json:"domain,omitempty"`
	// User name of the interactive console session, empty when nobody is logged on. Personal data.
	LoggedOnUser  string `protobuf:"bytes,15,opt,name=logged_on_user,json=loggedOnUser,proto3" json:"logged_on_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *Inventory) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Inventory) GetOs() *OsInfo {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *Inventory) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *Inventory) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Inventory) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Inventory) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *Inventory) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *Inventory) GetCpuLogicalProcessors() uint32 {
	if x != nil {
		return x.CpuLogicalProcessors
	}
	return 0
}

func (x *Inventory) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *Inventory) GetDisks() []*Disk {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *Inventory) GetNetworkInterfaces() []*NetworkInterface {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *Inventory) GetSoftware() []*SoftwareItem {
	if x != nil {
		return x.Software
	}
	return nil
}

func (x *Inventory) GetBootTime() *timestamppb.Timestamp {
	if x != nil {
		return x.BootTime
	}
	return nil
}

func (x *Inventory) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Inventory) GetLoggedOnUser() string {
	if x != nil {
		return x.LoggedOnUser
	}
	return ""
}

type Disk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mount         string                 `protobuf:"bytes,1,opt,name=mount,proto3" json:"mount,omitempty"`
	Filesystem    string                 `protobuf:"bytes,2,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FreeBytes     uint64                 `protobuf:"varint,4,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disk) Reset() {
	*x = Disk{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disk) ProtoMessage() {}

func (x *Disk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disk.ProtoReflect.Descriptor instead.
func (*Disk) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *Disk) GetMount() string {
	if x != nil {
		return x.Mount
	}
	return ""
}

func (x *Disk) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *Disk) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *Disk) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddresses   []string               `protobuf:"bytes,3,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInterface) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

type SoftwareItem struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version   string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Publisher string                 `protobuf:"bytes,3,opt,name=publisher,proto3" json:"publisher,omitempty"`
	// As reported by the OS, e.g. "20260114". Free text.
	InstallDate   string `protobuf:"bytes,4,opt,name=install_date,json=installDate,proto3" json:"install_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftwareItem) Reset() {
	*x = SoftwareItem{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareItem) ProtoMessage() {}

func (x *SoftwareItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareItem.ProtoReflect.Descriptor instead.
func (*SoftwareItem) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *SoftwareItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SoftwareItem) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SoftwareItem) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *SoftwareItem) GetInstallDate() string {
	if x != nil {
		return x.InstallDate
	}
	return ""
}

// A batch of results. The agent keeps the batch on disk until it receives a BatchAck with the same sequence.
// Sequence numbers are per endpoint, start at 1 and increase by one per batch; they survive agent restarts.
// Resending an acknowledged sequence is harmless: the server acknowledges it again without storing it twice.
// At most 500 results per batch.
type CheckResultBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Results       []*CheckResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResultBatch) Reset() {
	*x = CheckResultBatch{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResultBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResultBatch) ProtoMessage() {}

func (x *CheckResultBatch) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResultBatch.ProtoReflect.Descriptor instead.
func (*CheckResultBatch) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CheckResultBatch) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CheckResultBatch) GetResults() []*CheckResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type CheckResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CheckSpec.id from the signed configuration.
	CheckId string `protobuf:"bytes,1,opt,name=check_id,json=checkId,proto3" json:"check_id,omitempty"`
	// Configuration version the check ran under.
	ConfigVersion uint64                 `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	// Instance of the check, e.g. "C:" for a disk check over every drive; empty when not applicable.
	Target string `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	// Human-readable detail, e.g. "12.3 GB free of 237 GB".
	Detail string `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	// Non-empty when the check could not run; value is then meaningless.
	Error         string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResult) Reset() {
	*x = CheckResult{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResult) ProtoMessage() {}

func (x *CheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResult.ProtoReflect.Descriptor instead.
func (*CheckResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CheckResult) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

func (x *CheckResult) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *CheckResult) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *CheckResult) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CheckResult) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *CheckResult) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *CheckResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Sent only after the batch is committed to PostgreSQL.
type BatchAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAck) Reset() {
	*x = BatchAck{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAck) ProtoMessage() {}

func (x *BatchAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAck.ProtoReflect.Descriptor instead.
func (*BatchAck) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *BatchAck) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Sent when two thirds of the certificate lifetime has passed. Same key pair as the current certificate.
type RenewCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrDer        []byte                 `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertificateRequest) Reset() {
	*x = RenewCertificateRequest{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateRequest) ProtoMessage() {}

func (x *RenewCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateRequest.ProtoReflect.Descriptor instead.
func (*RenewCertificateRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *RenewCertificateRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type RenewCertificateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertificateDer []byte                 `protobuf:"bytes,1,opt,name=certificate_der,json=certificateDer,proto3" json:"certificate_der,omitempty"`
	// Non-empty when the renewal was refused; the agent keeps its current certificate and retries later.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertificateResponse) Reset() {
	*x = RenewCertificateResponse{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateResponse) ProtoMessage() {}

func (x *RenewCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateResponse.ProtoReflect.Descriptor instead.
func (*RenewCertificateResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *RenewCertificateResponse) GetCertificateDer() []byte {
	if x != nil {
		return x.CertificateDer
	}
	return nil
}

func (x *RenewCertificateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SignedConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized AgentConfig.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// ed25519 over "fleetify-agent-config-v1" || 0x00 || payload.
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	KeyId         string `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedConfig) Reset() {
	*x = SignedConfig{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedConfig) ProtoMessage() {}

func (x *SignedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedConfig.ProtoReflect.Descriptor instead.
func (*SignedConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *SignedConfig) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignedConfig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedConfig) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// The agent accepts a configuration only when the signature verifies against the pinned instance signing key,
// instance_id and endpoint_id equal its own, and version is higher than the applied version.
type AgentConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	InstanceId               string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	EndpointId               string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Version                  uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	IssuedAt                 *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	Tier                     Tier                   `protobuf:"varint,5,opt,name=tier,proto3,enum=fleetify.agent.v1.Tier" json:"tier,omitempty"`
	HeartbeatIntervalSeconds uint32                 `protobuf:"varint,6,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	InventoryIntervalSeconds uint32                 `protobuf:"varint,7,opt,name=inventory_interval_seconds,json=inventoryIntervalSeconds,proto3" json:"inventory_interval_seconds,omitempty"`
	// Always empty for TIER_AGENT_ONLY; the agent ignores checks on an agent-only configuration anyway.
	Checks        []*CheckSpec `protobuf:"bytes,8,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *AgentConfig) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AgentConfig) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *AgentConfig) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AgentConfig) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *AgentConfig) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *AgentConfig) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetInventoryIntervalSeconds() uint32 {
	if x != nil {
		return x.InventoryIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetChecks() []*CheckSpec {
	if x != nil {
		return x.Checks
	}
	return nil
}

type CheckSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CheckDefinition id.
	Id              string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            CheckType `protobuf:"varint,2,opt,name=type,proto3,enum=fleetify.agent.v1.CheckType" json:"type,omitempty"`
	IntervalSeconds uint32    `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	// Type-specific: CHECK_TYPE_DISK_FREE uses "drive" ("C:" or "*"), CHECK_TYPE_SERVICE_RUNNING uses "service",
	// CHECK_TYPE_CPU_USAGE uses optional "sample_seconds" (default 60, at most the interval).
	Parameters    map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSpec) Reset() {
	*x = CheckSpec{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSpec) ProtoMessage() {}

func (x *CheckSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSpec.ProtoReflect.Descriptor instead.
func (*CheckSpec) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *CheckSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckSpec) GetType() CheckType {
	if x != nil {
		return x.Type
	}
	return CheckType_CHECK_TYPE_UNSPECIFIED
}

func (x *CheckSpec) GetIntervalSeconds() uint32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *CheckSpec) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ConfigApplied struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion uint64                 `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// Non-empty when the agent refused the configuration (bad signature, wrong endpoint, old version).
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigApplied) Reset() {
	*x = ConfigApplied{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigApplied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigApplied) ProtoMessage() {}

func (x *ConfigApplied) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigApplied.ProtoReflect.Descriptor instead.
func (*ConfigApplied) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

func (x *ConfigApplied) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *ConfigApplied) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          DisconnectCode         `protobuf:"varint,1,opt,name=code,proto3,enum=fleetify.agent.v1.DisconnectCode" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *Disconnect) GetCode() DisconnectCode {
	if x != nil {
		return x.Code
	}
	return DisconnectCode_DISCONNECT_CODE_UNSPECIFIED
}

func (x *Disconnect) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x11fleetify.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12)\n" +
	"\x02os\x18\x04 \x01(\v2\x19.fleetify.agent.v1.OsInfoR\x02os\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\"\x9f\x02\n" +
	"\x0eEnrollResponse\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12'\n" +
	"\x0fcertificate_der\x18\x03 \x01(\fR\x0ecertificateDer\x12,\n" +
	"\x12ca_certificate_der\x18\x04 \x01(\fR\x10caCertificateDer\x12=\n" +
	"\x1binstance_signing_public_key\x18\x05 \x01(\fR\x18instanceSigningPublicKey\x125\n" +
	"\x17instance_signing_key_id\x18\x06 \x01(\tR\x14instanceSigningKeyId\"\x93\x01\n" +
	"\x06OsInfo\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tis_server\x18\x04 \x01(\bR\bisServer\x12\"\n" +
	"\farchitecture\x18\x05 \x01(\tR\farchitecture\"\xeb\x03\n" +
	"\fAgentMessage\x120\n" +
	"\x05hello\x18\x01 \x01(\v2\x18.fleetify.agent.v1.HelloH\x00R\x05hello\x12<\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1c.fleetify.agent.v1.HeartbeatH\x00R\theartbeat\x12B\n" +
	"\tinventory\x18\x03 \x01(\v2\".fleetify.agent.v1.InventoryReportH\x00R\tinventory\x12J\n" +
	"\rcheck_results\x18\x04 \x01(\v2#.fleetify.agent.v1.CheckResultBatchH\x00R\fcheckResults\x12Y\n" +
	"\x11renew_certificate\x18\x05 \x01(\v2*.fleetify.agent.v1.RenewCertificateRequestH\x00R\x10renewCertificate\x12I\n" +
	"\x0econfig_applied\x18\x06 \x01(\v2 .fleetify.agent.v1.ConfigAppliedH\x00R\rconfigApplied\x12-\n" +
	"\x04pong\x18\a \x01(\v2\x17.fleetify.agent.v1.PongH\x00R\x04pongB\x06\n" +
	"\x04body\"\xea\x03\n" +
	"\rServerMessage\x12:\n" +
	"\thello_ack\x18\x01 \x01(\v2\x1b.fleetify.agent.v1.HelloAckH\x00R\bhelloAck\x12:\n" +
	"\tbatch_ack\x18\x02 \x01(\v2\x1b.fleetify.agent.v1.BatchAckH\x00R\bbatchAck\x129\n" +
	"\x06config\x18\x03 \x01(\v2\x1f.fleetify.agent.v1.SignedConfigH\x00R\x06config\x12Z\n" +
	"\x11renew_certificate\x18\x04 \x01(\v2+.fleetify.agent.v1.RenewCertificateResponseH\x00R\x10renewCertificate\x12-\n" +
	"\x04ping\x18\x05 \x01(\v2\x17.fleetify.agent.v1.PingH\x00R\x04ping\x12?\n" +
	"\n" +
	"disconnect\x18\x06 \x01(\v2\x1d.fleetify.agent.v1.DisconnectH\x00R\n" +
	"disconnect\x12R\n" +
	"\x11inventory_request\x18\a \x01(\v2#.fleetify.agent.v1.InventoryRequestH\x00R\x10inventoryRequestB\x06\n" +
	"\x04body\"\xc1\x01\n" +
	"\x05Hello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12)\n" +
	"\x02os\x18\x03 \x01(\v2\x19.fleetify.agent.v1.OsInfoR\x02os\x12%\n" +
	"\x0econfig_version\x18\x04 \x01(\x04R\rconfigVersion\x12%\n" +
	"\x0einventory_hash\x18\x05 \x01(\tR\rinventoryHash\"\xa6\x01\n" +
	"\bHelloAck\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\rR\x18heartbeatIntervalSeconds\"F\n" +
	"\tHeartbeat\x129\n" +
	"\n" +
	"agent_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tagentTime\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\x12\n" +
	"\x10InventoryRequest\"a\n" +
	"\x0fInventoryReport\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12:\n" +
	"\tinventory\x18\x02 \x01(\v2\x1c.fleetify.agent.v1.InventoryR\tinventory\"\x86\x05\n" +
	"\tInventory\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12)\n" +
	"\x02os\x18\x02 \x01(\v2\x19.fleetify.agent.v1.OsInfoR\x02os\x12\"\n" +
	"\fmanufacturer\x18\x03 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12#\n" +
	"\rserial_number\x18\x05 \x01(\tR\fserialNumber\x12\x1b\n" +
	"\tcpu_model\x18\x06 \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tcpu_cores\x18\a \x01(\rR\bcpuCores\x124\n" +
	"\x16cpu_logical_processors\x18\b \x01(\rR\x14cpuLogicalProcessors\x12,\n" +
	"\x12memory_total_bytes\x18\t \x01(\x04R\x10memoryTotalBytes\x12-\n" +
	"\x05disks\x18\n" +
	" \x03(\v2\x17.fleetify.agent.v1.DiskR\x05disks\x12R\n" +
	"\x12network_interfaces\x18\v \x03(\v2#.fleetify.agent.v1.NetworkInterfaceR\x11networkInterfaces\x12;\n" +
	"\bsoftware\x18\f \x03(\v2\x1f.fleetify.agent.v1.SoftwareItemR\bsoftware\x127\n" +
	"\tboot_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\bbootTime\x12\x16\n" +
	"\x06domain\x18\x0e \x01(\tR\x06domain\x12$\n" +
	"\x0elogged_on_user\x18\x0f \x01(\tR\floggedOnUser\"|\n" +
	"\x04Disk\x12\x14\n" +
	"\x05mount\x18\x01 \x01(\tR\x05mount\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x02 \x01(\tR\n" +
	"filesystem\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x04 \x01(\x04R\tfreeBytes\"j\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12!\n" +
	"\fip_addresses\x18\x03 \x03(\tR\vipAddresses\"}\n" +
	"\fSoftwareItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tpublisher\x18\x03 \x01(\tR\tpublisher\x12!\n" +
	"\finstall_date\x18\x04 \x01(\tR\vinstallDate\"h\n" +
	"\x10CheckResultBatch\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x128\n" +
	"\aresults\x18\x02 \x03(\v2\x1e.fleetify.agent.v1.CheckResultR\aresults\"\xea\x01\n" +
	"\vCheckResult\x12\x19\n" +
	"\bcheck_id\x18\x01 \x01(\tR\acheckId\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\x04R\rconfigVersion\x12=\n" +
	"\fcollected_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"&\n" +
	"\bBatchAck\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"2\n" +
	"\x17RenewCertificateRequest\x12\x17\n" +
	"\acsr_der\x18\x01 \x01(\fR\x06csrDer\"Y\n" +
	"\x18RenewCertificateResponse\x12'\n" +
	"\x0fcertificate_der\x18\x01 \x01(\fR\x0ecertificateDer\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"]\n" +
	"\fSignedConfig\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\"\x81\x03\n" +
	"\vAgentConfig\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x127\n" +
	"\tissued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12+\n" +
	"\x04tier\x18\x05 \x01(\x0e2\x17.fleetify.agent.v1.TierR\x04tier\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x06 \x01(\rR\x18heartbeatIntervalSeconds\x12<\n" +
	"\x1ainventory_interval_seconds\x18\a \x01(\rR\x18inventoryIntervalSeconds\x124\n" +
	"\x06checks\x18\b \x03(\v2\x1c.fleetify.agent.v1.CheckSpecR\x06checks\"\x85\x02\n" +
	"\tCheckSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.fleetify.agent.v1.CheckTypeR\x04type\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\rR\x0fintervalSeconds\x12L\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2,.fleetify.agent.v1.CheckSpec.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\rConfigApplied\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x04R\rconfigVersion\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"[\n" +
	"\n" +
	"Disconnect\x125\n" +
	"\x04code\x18\x01 \x01(\x0e2!.fleetify.agent.v1.DisconnectCodeR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*C\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTIER_AGENT_ONLY\x10\x01\x12\x10\n" +
	"\fTIER_MANAGED\x10\x02*\xaf\x01\n" +
	"\tCheckType\x12\x1a\n" +
	"\x16CHECK_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CHECK_TYPE_CPU_USAGE\x10\x01\x12\x1b\n" +
	"\x17CHECK_TYPE_MEMORY_USAGE\x10\x02\x12\x18\n" +
	"\x14CHECK_TYPE_DISK_FREE\x10\x03\x12\x1e\n" +
	"\x1aCHECK_TYPE_SERVICE_RUNNING\x10\x04\x12\x15\n" +
	"\x11CHECK_TYPE_UPTIME\x10\x05*\xbf\x01\n" +
	"\x0eDisconnectCode\x12\x1f\n" +
	"\x1bDISCONNECT_CODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DISCONNECT_CODE_REVOKED\x10\x01\x12&\n" +
	"\"DISCONNECT_CODE_DUPLICATE_IDENTITY\x10\x02\x12#\n" +
	"\x1fDISCONNECT_CODE_SERVER_SHUTDOWN\x10\x03\x12\"\n" +
	"\x1eDISCONNECT_CODE_PROTOCOL_ERROR\x10\x04BiZJgithub.com/404-developer-AI/Fleeto/agent/internal/protocol/agentv1;agentv1\xaa\x02\x1aFleetify.Protocol.Agent.V1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_agent_proto_goTypes = []any{
	(Tier)(0),                        // 0: fleetify.agent.v1.Tier
	(CheckType)(0),                   // 1: fleetify.agent.v1.CheckType
	(DisconnectCode)(0),              // 2: fleetify.agent.v1.DisconnectCode
	(*EnrollRequest)(nil),            // 3: fleetify.agent.v1.EnrollRequest
	(*EnrollResponse)(nil),           // 4: fleetify.agent.v1.EnrollResponse
	(*OsInfo)(nil),                   // 5: fleetify.agent.v1.OsInfo
	(*AgentMessage)(nil),             // 6: fleetify.agent.v1.AgentMessage
	(*ServerMessage)(nil),            // 7: fleetify.agent.v1.ServerMessage
	(*Hello)(nil),                    // 8: fleetify.agent.v1.Hello
	(*HelloAck)(nil),                 // 9: fleetify.agent.v1.HelloAck
	(*Heartbeat)(nil),                // 10: fleetify.agent.v1.Heartbeat
	(*Ping)(nil),                     // 11: fleetify.agent.v1.Ping
	(*Pong)(nil),                     // 12: fleetify.agent.v1.Pong
	(*InventoryRequest)(nil),         // 13: fleetify.agent.v1.InventoryRequest
	(*InventoryReport)(nil),          // 14: fleetify.agent.v1.InventoryReport
	(*Inventory)(nil),                // 15: fleetify.agent.v1.Inventory
	(*Disk)(nil),                     // 16: fleetify.agent.v1.Disk
	(*NetworkInterface)(nil),         // 17: fleetify.agent.v1.NetworkInterface
	(*SoftwareItem)(nil),             // 18: fleetify.agent.v1.SoftwareItem
	(*CheckResultBatch)(nil),         // 19: fleetify.agent.v1.CheckResultBatch
	(*CheckResult)(nil),              // 20: fleetify.agent.v1.CheckResult
	(*BatchAck)(nil),                 // 21: fleetify.agent.v1.BatchAck
	(*RenewCertificateRequest)(nil),  // 22: fleetify.agent.v1.RenewCertificateRequest
	(*RenewCertificateResponse)(nil), // 23: fleetify.agent.v1.RenewCertificateResponse
	(*SignedConfig)(nil),             // 24: fleetify.agent.v1.SignedConfig
	(*AgentConfig)(nil),              // 25: fleetify.agent.v1.AgentConfig
	(*CheckSpec)(nil),                // 26: fleetify.agent.v1.CheckSpec
	(*ConfigApplied)(nil),            // 27: fleetify.agent.v1.ConfigApplied
	(*Disconnect)(nil),               // 28: fleetify.agent.v1.Disconnect
	nil,                              // 29: fleetify.agent.v1.CheckSpec.ParametersEntry
	(*timestamppb.Timestamp)(nil),    // 30: google.protobuf.Timestamp
}
var file_agent_proto_depIdxs = []int32{
	5,  // 0: fleetify.agent.v1.EnrollRequest.os:type_name -> fleetify.agent.v1.OsInfo
	8,  // 1: fleetify.agent.v1.AgentMessage.hello:type_name -> fleetify.agent.v1.Hello
	10, // 2: fleetify.agent.v1.AgentMessage.heartbeat:type_name -> fleetify.agent.v1.Heartbeat
	14, // 3: fleetify.agent.v1.AgentMessage.inventory:type_name -> fleetify.agent.v1.InventoryReport
	19, // 4: fleetify.agent.v1.AgentMessage.check_results:type_name -> fleetify.agent.v1.CheckResultBatch
	22, // 5: fleetify.agent.v1.AgentMessage.renew_certificate:type_name -> fleetify.agent.v1.RenewCertificateRequest
	27, // 6: fleetify.agent.v1.AgentMessage.config_applied:type_name -> fleetify.agent.v1.ConfigApplied
	12, // 7: fleetify.agent.v1.AgentMessage.pong:type_name -> fleetify.agent.v1.Pong
	9,  // 8: fleetify.agent.v1.ServerMessage.hello_ack:type_name -> fleetify.agent.v1.HelloAck
	21, // 9: fleetify.agent.v1.ServerMessage.batch_ack:type_name -> fleetify.agent.v1.BatchAck
	24, // 10: fleetify.agent.v1.ServerMessage.config:type_name -> fleetify.agent.v1.SignedConfig
	23, // 11: fleetify.agent.v1.ServerMessage.renew_certificate:type_name -> fleetify.agent.v1.RenewCertificateResponse
	11, // 12: fleetify.agent.v1.ServerMessage.ping:type_name -> fleetify.agent.v1.Ping
	28, // 13: fleetify.agent.v1.ServerMessage.disconnect:type_name -> fleetify.agent.v1.Disconnect
	13, // 14: fleetify.agent.v1.ServerMessage.inventory_request:type_name -> fleetify.agent.v1.InventoryRequest
	5,  // 15: fleetify.agent.v1.Hello.os:type_name -> fleetify.agent.v1.OsInfo
	30, // 16: fleetify.agent.v1.HelloAck.server_time:type_name -> google.protobuf.Timestamp
	30, // 17: fleetify.agent.v1.Heartbeat.agent_time:type_name -> google.protobuf.Timestamp
	15, // 18: fleetify.agent.v1.InventoryReport.inventory:type_name -> fleetify.agent.v1.Inventory
	5,  // 19: fleetify.agent.v1.Inventory.os:type_name -> fleetify.agent.v1.OsInfo
	16, // 20: fleetify.agent.v1.Inventory.disks:type_name -> fleetify.agent.v1.Disk
	17, // 21: fleetify.agent.v1.Inventory.network_interfaces:type_name -> fleetify.agent.v1.NetworkInterface
	18, // 22: fleetify.agent.v1.Inventory.software:type_name -> fleetify.agent.v1.SoftwareItem
	30, // 23: fleetify.agent.v1.Inventory.boot_time:type_name -> google.protobuf.Timestamp
	20, // 24: fleetify.agent.v1.CheckResultBatch.results:type_name -> fleetify.agent.v1.CheckResult
	30, // 25: fleetify.agent.v1.CheckResult.collected_at:type_name -> google.protobuf.Timestamp
	30, // 26: fleetify.agent.v1.AgentConfig.issued_at:type_name -> google.protobuf.Timestamp
	0,  // 27: fleetify.agent.v1.AgentConfig.tier:type_name -> fleetify.agent.v1.Tier
	26, // 28: fleetify.agent.v1.AgentConfig.checks:type_name -> fleetify.agent.v1.CheckSpec
	1,  // 29: fleetify.agent.v1.CheckSpec.type:type_name -> fleetify.agent.v1.CheckType
	29, // 30: fleetify.agent.v1.CheckSpec.parameters:type_name -> fleetify.agent.v1.CheckSpec.ParametersEntry
	2,  // 31: fleetify.agent.v1.Disconnect.code:type_name -> fleetify.agent.v1.DisconnectCode
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Inventory)(nil),
		(*AgentMessage_CheckResults)(nil),
		(*AgentMessage_RenewCertificate)(nil),
		(*AgentMessage_ConfigApplied)(nil),
		(*AgentMessage_Pong)(nil),
	}
	file_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerMessage_HelloAck)(nil),
		(*ServerMessage_BatchAck)(nil),
		(*ServerMessage_Config)(nil),
		(*ServerMessage_RenewCertificate)(nil),
		(*ServerMessage_Ping)(nil),
		(*ServerMessage_Disconnect)(nil),
		(*ServerMessage_InventoryRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
